from tkinter import *
from PIL import Image, ImageTk
#----------------------------------------------------------------------
window = Tk()
window.title("PVV Ingenieria")
window.config(background="white")
#----------------------------------------------------------------------
portada = Image.open("pvv_logo.png")
resized = portada.resize((150,100))
img_portada = ImageTk.PhotoImage(resized)
portada_label = Label(window, image=img_portada, background="orange")
#----------------------------------------------------------------------
def close_window():
    window.destroy()
exit = Button(window, text="Salir de la Aplicación", command=close_window)
exit.config(background="orange", borderwidth=0, activebackground="orange", font=15)
#----------------------------------------------------------------------
midlbl1 = Label(window, background="orange")
midlbl2 = Label(window, background="orange")
midlbl3 = Label(window, background="orange")
midlbl4 = Label(window, background="orange")
#----------------------------------------------------------------------
sidelbl1 = Label(window, background="orange")
sidelbl2 = Label(window, background="orange")
sidelbl3 = Label(window, background="orange")
sidelbl4 = Label(window, background="orange")
sidelbl5 = Label(window, background="orange")
sidelbl6 = Label(window, background="orange")
sidelbl7 = Label(window, background="orange")
sidelbl8 = Label(window, background="orange")
#----------------------------------------------------------------------
rightlbl1 = Label(window, background="orange")
rightlbl2 = Label(window, background="orange")
rightlbl3 = Label(window, background="orange")
rightlbl4 = Label(window, background="orange")
rightlbl5 = Label(window, background="orange")
rightlbl6 = Label(window, background="orange")
rightlbl7 = Label(window, background="orange")
rightlbl8 = Label(window, background="orange")
#----------------------------------------------------------------------
finanzas_logo = Image.open("finanzas.png")
finanzas_rsize = finanzas_logo.resize((125,125))
finanzas_icon = ImageTk.PhotoImage(finanzas_rsize)

comercial_logo = Image.open("comercial.png")
comercial_rsize = comercial_logo.resize((125,125))
comercial_icon = ImageTk.PhotoImage(comercial_rsize)

operaciones_logo = Image.open("operaciones.png")
operaciones_rsize = operaciones_logo.resize((125,125))
operaciones_icon = ImageTk.PhotoImage(operaciones_rsize)

gestion_logo = Image.open("gestion.png")
gestion_rsize = gestion_logo.resize((125,125))
gestion_icon = ImageTk.PhotoImage(gestion_rsize)

caphumano_logo = Image.open("caphumano.png")
caphumano_rsize = caphumano_logo.resize((125,125))
caphumano_icon = ImageTk.PhotoImage(caphumano_rsize)

ecommerce_logo = Image.open("ecommerce.png")
ecommerce_rsize = ecommerce_logo.resize((125,125))
ecommerce_icon = ImageTk.PhotoImage(ecommerce_rsize)

capacitaciones_logo = Image.open("capacitaciones.png")
capacitaciones_rsize = capacitaciones_logo.resize((125,125))
capacitaciones_icon = ImageTk.PhotoImage(capacitaciones_rsize)
#----------------------------------------------------------------------
window.columnconfigure((0,1,2,3,4,5), weight=200)
window.rowconfigure(0, weight= 200)
window.rowconfigure(1, weight= 200)
window.rowconfigure(2, weight= 200)
window.rowconfigure(3, weight= 200)
window.rowconfigure(4, weight= 200)
window.rowconfigure(5, weight= 200)
window.rowconfigure(6, weight= 200)
window.rowconfigure(7, weight= 200)
window.rowconfigure(8, weight= 200)
#----------------------------------------------------------------------
txt1 = Label(window, text="Información\n Financiera\n y Contabilidad", background="white")
txt2 = Label(window, text="Control\n de\n Ventas", background="white")
txt3 = Label(window, text="Detalles Operacionales\n Internos\n y Externos", background="white")
txt4 = Label(window, text="Control\n de la\n Gestión Empresarial", background="white")
txt5 = Label(window, text="Control\n y Gestión\n del Equipo Humano", background="white")
txt6 = Label(window, text="Marketplace", background="white")
txt7 = Label(window, text="Planificación y\n Gestión de\nCapacitaciones", background="white")
#----------------------------------------------------------------------
boton1 = Button(window, text="Ingresar", background="orange", activebackground="yellow")
boton2 = Button(window, text="Ingresar", background="orange", activebackground="yellow")
boton3 = Button(window, text="Ingresar", background="orange", activebackground="yellow")
boton4 = Button(window, text="Ingresar", background="orange", activebackground="yellow")
boton5 = Button(window, text="Ingresar", background="orange", activebackground="yellow")
boton6 = Button(window, text="Ingresar", background="orange", activebackground="yellow")
boton7 = Button(window, text="Ingresar", background="orange", activebackground="yellow")
#----------------------------------------------------------------------
finanzas_title = Label(window, text="Finanzas", background="white")
finanzas_title.config(font=("Arial", 20))
comercial_title = Label(window, text="Comercial", background="white")
comercial_title.config(font=("Arial", 20))
operaciones_title = Label(window, text="Operaciones", background="white")
operaciones_title.config(font=("Arial", 20))
gestion_title = Label(window, text="Gestión", background="white")
gestion_title.config(font=("Arial", 20))
caphumano_title = Label(window, text="Gestión\nCapital Humano", background="white")
caphumano_title.config(font=("Arial", 20))
ecommerce_title = Label(window, text="E-Commerce", background="white")
ecommerce_title.config(font=("Arial", 20))
capacitacion_title = Label(window, text="Capcitaciones", background="white")
capacitacion_title.config(font=("Arial", 20))
#----------------------------------------------------------------------
img1 = Label(window, image=finanzas_icon, background="white")
img2 = Label(window, image=comercial_icon, background="white")
img3 = Label(window, image=operaciones_icon, background="white")
img4 = Label(window, image=gestion_icon, background="white")
img5 = Label(window, image=caphumano_icon, background="white")
img6 = Label(window, image=ecommerce_icon, background="white")
img7 = Label(window, image=capacitaciones_icon, background="white")
#----------------------------------------------------------------------
portada_label.grid(column=0, row=0, sticky="nsew")
exit.grid(column=5, row=0, sticky="nsew")
midlbl1.grid(column=1, row=0, sticky="nsew")
midlbl2.grid(column=2, row=0, sticky="nsew")
midlbl3.grid(column=3, row=0, sticky="nsew")
midlbl4.grid(column=4, row=0, sticky="nsew")
#----------------------------------------------------------------------
sidelbl1.grid(column=0, row=1, sticky="nsew")
sidelbl2.grid(column=0, row=2, sticky="nsew")
sidelbl3.grid(column=0, row=3, sticky="nsew")
sidelbl4.grid(column=0, row=4, sticky="nsew")
sidelbl5.grid(column=0, row=5, sticky="nsew")
sidelbl6.grid(column=0, row=6, sticky="nsew")
sidelbl7.grid(column=0, row=7, sticky="nsew")
sidelbl8.grid(column=0, row=8, sticky="nsew")
#----------------------------------------------------------------------
rightlbl1.grid(column=5, row=1, sticky="nsew")
rightlbl2.grid(column=5, row=2, sticky="nsew")
rightlbl3.grid(column=5, row=3, sticky="nsew")
rightlbl4.grid(column=5, row=4, sticky="nsew")
rightlbl5.grid(column=5, row=5, sticky="nsew")
rightlbl6.grid(column=5, row=6, sticky="nsew")
rightlbl7.grid(column=5, row=7, sticky="nsew")
rightlbl8.grid(column=5, row=8, sticky="nsew")
#----------------------------------------------------------------------
finanzas_title.grid(row=1, column=1)
comercial_title.grid(row=1, column=2)
operaciones_title.grid(row=1, column=3)
gestion_title.grid(row=1, column=4)
caphumano_title.grid(row=5, column=1)
ecommerce_title.grid(row=5, column=2)
capacitacion_title.grid(row=5, column=3)
#----------------------------------------------------------------------
img1.grid(row=2, column=1)
img2.grid(row=2, column=2)
img3.grid(row=2, column=3)
img4.grid(row=2, column=4)
img5.grid(row=6, column=1)
img6.grid(row=6, column=2)
img7.grid(row=6, column=3)
#----------------------------------------------------------------------
txt1.grid(row=3, column=1)
txt2.grid(row=3, column=2)
txt3.grid(row=3, column=3)
txt4.grid(row=3, column=4)
txt5.grid(row=7, column=1)
txt6.grid(row=7, column=2)
txt7.grid(row=7, column=3)
boton1.grid(row=4, column=1)
boton2.grid(row=4, column=2)
boton3.grid(row=4, column=3)
boton4.grid(row=4, column=4)
boton5.grid(row=8, column=1)
boton6.grid(row=8, column=2)
boton7.grid(row=8, column=3)
#----------------------------------------------------------------------
window.mainloop()

